[tool.poetry]
name = "aistream"
version = "0.1.0"
description = ""
authors = ["Premanath Talamarla <premanath@syoft.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
streamlit = "^1.39.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
